// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listPorts: () => __TAURI_INVOKE<string[]>("list_ports"),
	connectPort: (portPath: string, pollIntervalMs: number | null) => typedError<null, string>(__TAURI_INVOKE("connect_port", { portPath, pollIntervalMs })),
	disconnectPort: () => typedError<null, string>(__TAURI_INVOKE("disconnect_port")),
	setLoadOn: (on: boolean) => typedError<null, string>(__TAURI_INVOKE("set_load_on", { on })),
	setCurrent: (amps: number | null) => typedError<null, string>(__TAURI_INVOKE("set_current", { amps })),
	setCutoffVoltage: (volts: number | null) => typedError<null, string>(__TAURI_INVOKE("set_cutoff_voltage", { volts })),
	setTimeoutSeconds: (seconds: number) => typedError<null, string>(__TAURI_INVOKE("set_timeout_seconds", { seconds })),
	resetCounters: () => typedError<null, string>(__TAURI_INVOKE("reset_counters")),
	exportXlsx: (path: string, times: (number | null)[], voltage: (number | null)[], current: (number | null)[], power: (number | null)[]) => typedError<null, string>(__TAURI_INVOKE("export_xlsx", { path, times, voltage, current, power })),
};

/** Events */
export const events = {
	connectionStatusEvent: makeEvent<ConnectionStatusEvent_Deserialize>("connection-status-event"),
	deviceDataEvent: makeEvent<DeviceDataEvent>("device-data-event"),
};

/* Types */
export type ConnectionStatusEvent = ConnectionStatusEvent_Serialize | ConnectionStatusEvent_Deserialize;

export type ConnectionStatusEvent_Deserialize = {
	connected: boolean,
	error: string | null,
	stage: string | null,
	attempt: number | null,
	maxAttempts: number | null,
};

export type ConnectionStatusEvent_Serialize = {
	connected: boolean,
	error: string | null,
	stage?: string | null,
	attempt?: number | null,
	maxAttempts?: number | null,
};

export type DeviceDataEvent = {
	type: string,
	voltageV: number | null,
	currentA: number | null,
	capacityMAh: number | null,
	powerW: number | null,
	tempC: number | null,
	runtimeS: number,
	energyWh: number | null,
	isOn: boolean,
	setCurrentA: number | null,
	setCutoffV: number | null,
	setTimerS: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

